# Generated by Django 3.1.1 on 2021-02-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='ThatsSoVeda', max_length=255),
        ),
    ]
