# Generated by Django 3.1.1 on 2021-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0006_auto_20210226_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='This is the snippet ...', max_length=255),
        ),
    ]
