# Generated by Django 3.1.1 on 2021-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0009_post_post_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotographyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
