# Generated by Django 3.1.1 on 2021-04-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0013_auto_20210330_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
