# Generated by Django 3.1.1 on 2022-11-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0015_auto_20221108_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
