# Generated by Django 3.1.1 on 2022-12-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0017_remove_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potographypost',
            old_name='food_image',
            new_name='commissioned_Image',
        ),
        migrations.RenameField(
            model_name='potographypost',
            old_name='landscape_image',
            new_name='digital_Image',
        ),
        migrations.RenameField(
            model_name='potographypost',
            old_name='portrait_image',
            new_name='film_Photography',
        ),
    ]
