# Generated by Django 3.1.1 on 2022-12-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0018_auto_20221213_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potographypost',
            old_name='commissioned_Image',
            new_name='food_image',
        ),
        migrations.RenameField(
            model_name='potographypost',
            old_name='digital_Image',
            new_name='landscape_image',
        ),
        migrations.RenameField(
            model_name='potographypost',
            old_name='film_Photography',
            new_name='portrait_image',
        ),
    ]
