# Generated by Django 3.1.1 on 2021-03-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0010_potographypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='potographypost',
            name='landscape_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
