# Generated by Django 3.1.1 on 2021-03-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0011_potographypost_landscape_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='potographypost',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
