# Generated by Django 3.1.1 on 2021-03-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veda', '0012_potographypost_food_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_img',
            new_name='Blog_cover_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_img1',
            new_name='Blog_post_image_1',
        ),
        migrations.AddField(
            model_name='post',
            name='Blog_post_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Blog_post_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Blog_post_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Blog_post_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='Blog_post_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
